### PR TITLE
icwt implementation

### PR DESCRIPTION
**Pull request by jaredbryan881**
I added an icwt function based on Torrence and Compo, 1998 (and its implementation in pycwt). I also updated the cwt function to use Julia 1.0, e.g. changed flipdim() to reverse(), and changed how scales and frequencies are defined. The original purpose of these changes was to have consistent wavelet transform results between Python and Julia, so the implementation closely resembles that in pycwt.

### CODE REVIEW

**Comment by dsweber2** [comment]
Cool. Do you plan on writing some tests comparing with pycwt? I think the default values you've included for the sampling info make sense.

**Comment by jaredbryan881** [comment]
I am planning on formalizing the tests at some point (and can include these in a future PR), though the pycwt implementation currently has some minor bugs that make 1:1 comparison slightly tricky. I will create some tests comparing the output of a corrected version of pycwt with the implementation here. In the mean time, I can create a simple test that checks the similarity between an input waveform and a waveform after transform and inverse transform. I am open to other ideas for tests or improvements!

**Comment by dsweber2** [comment]
I'm glad you found an alternative to compare to that isn't matlab. Some other tests we could do is computing the expected results on cosines and delta spikes analytically, and compare with that.

The package itself could use a port to read the docs or something like that.

I've been thinking about implementing 2D wavelets one of these days, so if you're feeling really gungho, that would be good to have.

**Comment by jaredbryan881** [comment]
Great, I will keep these ideas in mind!

**Pull request merged**
